routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/user/profile', [App\Http\Controllers\HomeController::class, 'showProfile'])->name('profile');
Route::post('/user/profile', [App\Http\Controllers\HomeController::class, 'updateProfile'])->name('updateProfile');
Route::post('/user/change-password', [App\Http\Controllers\HomeController::class, 'updatePassword'])->name('updatePassword');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', App\Http\Controllers\RoleController::class);
    Route::resource('users', App\Http\Controllers\UserController::class);
    Route::resource('products', App\Http\Controllers\ProductController::class);
    Route::resource('categories', App\Http\Controllers\CategoryController::class);
    Route::resource('brands', App\Http\Controllers\BrandController::class);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Brand;
use App\Models\Category;
use App\Models\ProductReview;
use App\Models\ProductImage;

class Product extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id',
        'brand_id',
        'category_id',
        'productName',
        'productDescription',
        'productPrice',
        'productStatus',
    ];

    /**
     * Get the user that owns the phone.
     */
    public function brand()
    {
        return $this->belongsTo(Brand::class,'brand_id');
    }

    /**
     * Get the user that owns the phone.
     */
    public function category()
    {
        return $this->belongsTo(Category::class,'category_id');
    }

    /**
     * Get the user that owns the phone.
     */
    public function product_images()
    {
        return $this->hasMany(ProductImage::class,'product_id');
    }

    /**
     * Get the user that owns the phone.
     */
    public function reviews()
    {
        return $this->hasMany(ProductReview::class);
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\ProductReview;
use App\Models\Brand;
use App\Models\Category;
use App\Models\ProductImage;
use Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:product-list|product-create|product-edit|product-delete', ['only' => ['index','show']]);
        $this->middleware('permission:product-create', ['only' => ['create','store']]);
        $this->middleware('permission:product-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:product-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::latest()->paginate(2);
        return view('products.index',compact('products'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $brands = Brand::where('brandStatus',1)->get();
        $categories = Category::where('categoryStatus',1)->get();
        return view('products.create',compact('brands','categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'productName' => 'required',
            'brand_id' => 'required',
            'category_id' => 'required',
            'productDescription' => 'required',
            'productPrice' => 'required|numeric',
        ]);

        Product::create($request->all());

        return redirect()->route('products.index')
                        ->with('success','Product created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        $brands = Brand::where('brandStatus',1)->get();
        $categories = Category::where('categoryStatus',1)->get();
        return view('products.show',compact('product','brands','categories'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $brands = Brand::where('brandStatus',1)->get();
        $categories = Category::where('categoryStatus',1)->get();
        return view('products.edit',compact('product','brands','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'brand_id' => 'required',
            'category_id' => 'required',
            'productName' => 'required',
            'productDescription' => 'required',
            'productPrice' => 'required|numeric',
        ]);

        $product = Product::find($id);
        $product->update($request->all());

        $filePath = "uploads/products/$product->id";

        if(!empty($request->images)){
            foreach($request->images as $key => $image) {
                $extension = $request->images[$key]->extension();
                $fileName = "product-" . uniqid() . '.' . $extension;
                $url = "$filePath/$fileName";

                $upload_image = Storage::disk('public_uploads')->put($url, file_get_contents($image), 'public');

                if($upload_image) {
                    $imageData = ['product_id' => $product->id, 'image' => $url];
                    $productImage = ProductImage::create($imageData);
                }
            }
        }

        return redirect()->route('products.index')
                        ->with('success','Product updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      //  $product = ProductReview::where('product_id',$id)->delete();
        $product = Product::findOrFail($id);
        $product->delete();

        return true;
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>{{ __('Products Create') }}</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Products</a></li>
                <li class="breadcrumb-item active">{{ __('Products Create') }}</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 margin-tb">
                                <h3 class="card-title">{{ __('Add new Product') }}</h3>
                            </div>
                            <div class="col-lg-6 col-md-6 margin-tb">
                            </div>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form class="form-horizontal"action="{{ route('products.store') }}" method="POST" enctype='multipart/form-data'>
    	                @csrf
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="productName" class="col-sm-2 col-form-label">Name</label>
                                <div class="col-sm-10">
                                    <input type="text" name="productName" class="form-control  @error('productName') is-invalid @enderror" placeholder="Name">

                                    @error('productName')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="productPrice" class="col-sm-2 col-form-label">Price</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control @error('productPrice') is-invalid @enderror" name="productPrice" placeholder="Price">
                                    @error('productPrice')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="productDescription" class="col-sm-2 col-form-label">Brand</label>
                                <div class="col-sm-10">
                                    <select class="custom-select @error('brand_id') is-invalid @enderror" name="brand_id">
                                    <option value=""> -- Select Brand --</option>
                                    @foreach($brands as $brand)
                                        <option value="{{$brand->id}}">{{ $brand->brandName }}</option>
                                    @endforeach
                                    </select>
                                    @error('brand_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="productDescription" class="col-sm-2 col-form-label">Category</label>
                                <div class="col-sm-10">
                                    <select class="custom-select @error('category_id') is-invalid @enderror" name="category_id">
                                    <option value=""> -- Select Category --</option>
                                    @foreach($categories as $category)
                                        <option value="{{$category->id}}">{{ $category->categoryName }}</option>
                                    @endforeach
                                    </select>
                                    @error('category_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="productDescription" class="col-sm-2 col-form-label">Detail</label>
                                <div class="col-sm-10">
                                    <textarea class="form-control @error('productDescription') is-invalid @enderror" style="height:150px" name="productDescription" placeholder="Detail"></textarea>
                                    @error('productDescription')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="exampleInputFile" class="col-sm-2 col-form-label">Image</label>
                                <div class="col-sm-10">
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input file-input" name="images[]" id="exampleInputFile" multiple>
                                            <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row img-preview">
                            </div>
                            <input type="hidden" name="productStatus" class="form-control" placeholder="Product Status" value="1">
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-info">Save</button>
                            <a href="{{ route('products.index')}}" class="btn btn-default float-right">Cancel</a>
                        </div>
                        <!-- /.card-footer -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<script>

    function previewImages() {

        var $preview = $('.img-preview').empty();
        if (this.files) $.each(this.files, readAndPreview);

        function readAndPreview(i, file) {

        if (!/\.(jpe?g|png|gif)$/i.test(file.name)){

            return swal("Opps!", file.name + " is not an image.", "warning");
        } // else...

        var reader = new FileReader();

        $(reader).on("load", function() {
            $preview.append(
                '<div class="col-md-2">' +
                    '<img src="'+ this.result +'" class="img-fluid img-thumbnail" alt="image">' +
                '</div>'
            ); //$("<img/>", {src:this.result, height:100})
        });

        reader.readAsDataURL(file);

        }

    }
    $('.file-input').on("change", previewImages);
</script>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>{{ __('Products Edit') }}</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Products</a></li>
                <li class="breadcrumb-item active">{{ __('Products Edit') }}</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 margin-tb">
                                <h3 class="card-title">{{ __('Edit Product') }}</h3>
                            </div>
                            <div class="col-lg-6 col-md-6 margin-tb">
                            </div>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form class="form-horizontal" action="{{ route('products.update',$product->id) }}" method="POST" enctype='multipart/form-data'>
                        @csrf
                        @method('PUT')
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="productName" class="col-sm-2 col-form-label">Name</label>
                                <div class="col-sm-10">
                                    <input type="text" name="productName" class="form-control" value="{{ $product->productName }}" placeholder="Name">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="productPrice" class="col-sm-2 col-form-label">Price</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="productPrice" value="{{ $product->productPrice }}" placeholder="Price">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="productDescription" class="col-sm-2 col-form-label">Brand</label>
                                <div class="col-sm-10">
                                    <select class="custom-select" name="brand_id">
                                    @foreach($brands as $brand)
                                        <option value="{{$brand->id}}" @if($brand->id == $product->brand_id) selected @endif>{{ $brand->brandName }}</option>
                                    @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="productDescription" class="col-sm-2 col-form-label">Category</label>
                                <div class="col-sm-10">
                                    <select class="custom-select" name="category_id">
                                    @foreach($categories as $category)
                                        <option value="{{$category->id}}" @if($category->id == $product->category_id) selected @endif>{{ $category->categoryName }}</option>
                                    @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="productDescription" class="col-sm-2 col-form-label">Detail</label>
                                <div class="col-sm-10">
                                    <textarea class="form-control" style="height:150px" name="productDescription" placeholder="Detail"> {{ $product->productDescription }} </textarea>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="exampleInputFile" class="col-sm-2 col-form-label">Image</label>
                                <div class="col-sm-10">
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input file-input" name="images[]" id="exampleInputFile" multiple>
                                            <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row img-preview">
                                @foreach($product->product_images as $val)
                                <div class="col-md-2">
                                    <img src="{{ asset($val->image)}}" class="img-fluid img-thumbnail" alt="image">
                                </div>
                                @endforeach
                            </div>
                            <input type="hidden" name="productStatus" class="form-control" placeholder="Product Status" value="1">
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-info">Save</button>
                            <a href="{{ route('products.index')}}" class="btn btn-default float-right">Cancel</a>
                        </div>
                        <!-- /.card-footer -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<script>

    function previewImages() {

        var $preview = $('.img-preview');
        if (this.files) $.each(this.files, readAndPreview);

        function readAndPreview(i, file) {

        if (!/\.(jpe?g|png|gif)$/i.test(file.name)){

            return swal("Opps!", file.name + " is not an image.", "warning");
        } // else...

        var reader = new FileReader();

        $(reader).on("load", function() {
            $preview.append(
                '<div class="col-md-2">' +
                    '<img src="'+ this.result +'" class="img-fluid img-thumbnail" alt="image">' +
                '</div>'
            ); //$("<img/>", {src:this.result, height:100})
        });

        reader.readAsDataURL(file);

        }

    }
    $('.file-input').on("change", previewImages);
</script>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>{{ __('Products View') }}</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Products</a></li>
                <li class="breadcrumb-item active">{{ __('Products View') }}</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 margin-tb">
                                <h3 class="card-title">{{ __('View Product') }}</h3>
                            </div>
                            <div class="col-lg-6 col-md-6 margin-tb">
                            </div>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form class="form-horizontal" action="{{ route('products.update',$product->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="productName" class="col-sm-2 col-form-label">Name</label>
                                <div class="col-sm-10">
                                    <input type="text" name="productName" class="form-control" value="{{ $product->productName }}" placeholder="Name" disabled>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="productPrice" class="col-sm-2 col-form-label">Price</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="productPrice" value="{{ $product->productPrice }}" placeholder="Price" disabled>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="productDescription" class="col-sm-2 col-form-label">Brand</label>
                                <div class="col-sm-10">
                                    <select class="custom-select" name="brand_id" disabled>
                                    @foreach($brands as $brand)
                                        <option value="{{$brand->id}}" @if($brand->id == $product->brand_id) selected @endif>{{ $brand->brandName }}</option>
                                    @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="productDescription" class="col-sm-2 col-form-label">Category</label>
                                <div class="col-sm-10">
                                    <select class="custom-select" name="category_id" disabled>
                                    @foreach($categories as $category)
                                        <option value="{{$category->id}}" @if($category->id == $product->category_id) selected @endif>{{ $category->categoryName }}</option>
                                    @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="productDescription" class="col-sm-2 col-form-label">Detail</label>
                                <div class="col-sm-10">
                                    <textarea class="form-control" style="height:150px" name="productDescription" placeholder="Detail" disabled> {{ $product->productDescription }} </textarea>
                                </div>
                            </div>

                            <input type="hidden" name="productStatus" class="form-control" placeholder="Product Status" value="1">
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <a href="{{ route('products.index')}}" class="btn btn-default float-right">Back</a>
                        </div>
                        <!-- /.card-footer -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection